In [1]:
import numpy as np
import random

In [5]:
def loadDataSet(fileName):
    dataMat =[]
    fr = open(fileName)
    for line in fr.readlines():
        curLine = line.strip().split("\t")
        fltLine = list(map(float,curLine))
        dataMat.append(fltLine)
    return dataMat

In [3]:
def eDistance(vecA,vecB):
    vecB = np.array(vecB)
    return np.sqrt(np.sum(np.power(vecA-vecB,2)))

In [4]:
def distancePointToClosestCenter(x,centroids):
    result = eDistance(x,centroids[0])
    for centroid in centroids[1:]:
        distance = eDistance(x,centroid)
        if distance < result:
            result = distance
    return result

In [27]:
def selectInitialCenter(dataSet,k):
    dataSize = dataSet.shape[0]
    centroids = []
    total = 0
    randomIndex= random.choice(range(dataSize))
    firstCenter = dataSet[randomIndex]
    centroids.append(firstCenter)
    while len(centroids) < k:
        weights = [distancePointToClosestCenter(x,centroids) for x in dataSet]
        total = np.sum(weights)
        weights = [x/ total for x in weights]
        print(len(weights))
        num = random.random()
        total = 0
        x = -1
        while  total < num:
            x +=1
            total +=weights[x]
        centroids.append(dataSet[x])
    return centroids

In [16]:
fileName = "testSet.txt"
dataList = loadDataSet(fileName)
dataMat = np.mat(dataList)

In [17]:
dataMat.shape

(80, 2)

In [28]:
cent = selectInitialCenter(dataMat,3)

80
80


In [24]:
cent

[matrix([[-2.651229, -3.103198]]),
 matrix([[ 4.479332, -1.764772]]),
 matrix([[ 4.208187,  2.984927]]),
 matrix([[-1.616805,  3.573188]])]